# Generated by Django 5.2.1 on 2025-09-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referralearning_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralearning',
            options={'ordering': ['-created_at']},
        ),
    ]
