# Generated by Django 5.2.1 on 2025-09-08 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referralearning_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred', 'level')},
        ),
    ]
