# Generated by Django 5.2.1 on 2025-09-17 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_referral_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiontier',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Direct (Level 1)'), (2, 'Indirect (Level 2)'), (3, 'Level 3')], default=1),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='commissiontier',
            index=models.Index(fields=['level', 'earning_type'], name='referrals_c_level_b5145c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'level'], name='referrals_r_referre_2dd16f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralearning',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_0e72a8_idx'),
        ),
    ]
