# Generated by Django 5.2.1 on 2025-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskwallet_taskwallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskwallet',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
