# Generated by Django 5.2.1 on 2025-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskwallet_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskwallet',
            name='reference',
        ),
        migrations.AddField(
            model_name='taskwallettransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
