# Generated by Django 5.2.1 on 2025-09-17 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskwallet_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='tasks_submi_status_d702e6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='tasks_task_status_e8ffa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('task', 'member'), name='unique_submission_per_member'),
        ),
    ]
