# Generated by Django 5.2.1 on 2025-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sample_image',
            field=models.ImageField(blank=True, help_text='Optional sample image for the task', null=True, upload_to='task_samples/images/'),
        ),
        migrations.AddField(
            model_name='task',
            name='sample_link',
            field=models.URLField(blank=True, help_text='Optional link (e.g., website, Google Doc, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video link', null=True),
        ),
    ]
