# Generated by Django 5.2.1 on 2025-08-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marketing_emails',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_notifications',
        ),
    ]
