# Generated by Django 5.2.1 on 2025-08-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tasks_posted',
        ),
    ]
