# Generated by Django 5.2.1 on 2025-08-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_tasks_completed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_referra_98b351_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
