# Generated by Django 5.2.1 on 2025-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('advertiser', 'Advertiser')], db_index=True, default='member', max_length=20),
        ),
    ]
