# Generated by Django 5.2.1 on 2025-09-26 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_preferred_currency_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_phone_af6883_idx',
        ),
        migrations.AlterField(
            model_name='phoneverificationtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating (0–5 scale)', max_digits=2),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage success rate (0–100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.skill'),
        ),
    ]
