# Generated by Django 5.2.1 on 2025-09-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_skill_remove_user_users_email_4b85f2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('GHS', 'GHS'), ('KES', 'KES'), ('USD', 'USD')], default='NGN', max_length=3),
        ),
    ]
