# Generated by Django 5.2.1 on 2025-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'Payment Gateway', 'verbose_name_plural': 'Payment Gateways'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='paystacktransaction',
            options={'verbose_name': 'Paystack Transaction', 'verbose_name_plural': 'Paystack Transactions'},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Event', 'verbose_name_plural': 'Webhook Events'},
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_reference',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='paystack_reference',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
