# Generated by Django 5.2.1 on 2025-09-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentgateway_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterwaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.URLField(blank=True)),
                ('flutterwave_id', models.CharField(blank=True, max_length=255)),
                ('flutterwave_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('transfer_id', models.CharField(blank=True, max_length=255)),
                ('beneficiary_id', models.CharField(blank=True, max_length=255)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flutterwave_details', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Flutterwave Transaction',
                'verbose_name_plural': 'Flutterwave Transactions',
                'db_table': 'flutterwave_transactions',
            },
        ),
    ]
