# Generated by Django 5.2.1 on 2025-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_flutterwavetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
