# Generated by Django 5.2.1 on 2025-09-26 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_currencyrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='category',
            field=models.CharField(choices=[('funding', 'User Funding'), ('withdrawal', 'User Withdrawal'), ('task_payment', 'Task Payment'), ('task_earning', 'Task Earning'), ('referral_bonus', 'Referral Bonus'), ('escrow', 'Escrow'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('company_cut', 'Company Cut')], default='funding', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='internal_reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'created_at'], name='payment_tra_user_id_ec207b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
    ]
