# Generated by Django 5.2.1 on 2025-09-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='amount',
            new_name='amount_usd',
        ),
    ]
