# Generated by Django 5.2.1 on 2025-09-26 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_amount_paymenttransaction_amount_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='internal_reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
