# Generated by Django 5.2.1 on 2025-09-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymenttransaction_internal_reference'),
        ('tasks', '0005_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount_local',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=15),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
