# Generated by Django 5.2.1 on 2025-09-30 07:16

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymenttransaction_amount_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_reference',
            field=models.CharField(db_index=True, default=payments.models.generate_gateway_reference, max_length=100, unique=True),
        ),
    ]
