# Generated by Django 5.2.1 on 2025-09-30 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_paymenttransaction_gateway_reference'),
        ('tasks', '0005_alter_submission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('gateway_reference',), name='uniq_gateway_reference'),
        ),
    ]
