# Generated by Django 5.2.1 on 2025-09-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymenttransaction_uniq_gateway_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhookevent',
            unique_together={('gateway', 'reference', 'event_type')},
        ),
    ]
