# Generated by Django 5.2.1 on 2025-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_webhookevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['gateway', 'reference', 'processed'], name='webhook_eve_gateway_61bc68_idx'),
        ),
    ]
