# Generated by Django 5.2.1 on 2025-10-01 22:01

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_paymenttransaction_gateway_response_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='uniq_gateway_reference',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_reference',
            field=models.CharField(db_index=True, default=payments.models.generate_gateway_reference, max_length=100),
        ),
    ]
