# Generated by Django 5.2.1 on 2025-08-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskwallet_reference_and_more'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowtransaction',
            name='escrow_transaction',
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='taskwallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='tasks.taskwallettransaction'),
        ),
    ]
