# Generated by Django 5.2.1 on 2025-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_escrowtransaction_escrow_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('task_payment', 'Task Payment'), ('task_earning', 'Task Earning'), ('referral_bonus', 'Referral Bonus'), ('withdrawal', 'Withdrawal'), ('escrow', 'Escrow'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('company_cut', 'company_cut')], max_length=20),
        ),
    ]
