# Generated by Django 5.2.1 on 2025-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_transaction_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('task_payment', 'Task Payment'), ('task_earning', 'Task Earning'), ('referral_bonus', 'Referral Bonus'), ('withdrawal', 'Withdrawal'), ('funding', 'Funding'), ('escrow', 'Escrow'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('company_cut', 'Company Cut')], max_length=20),
        ),
    ]
