# Generated by Django 5.2.1 on 2025-09-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_escrowtransaction_advertiser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at', '-processed_at']},
        ),
    ]
