# Generated by Django 5.2.1 on 2025-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_withdrawalrequest_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_local',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
