# Generated by Django 5.2.1 on 2025-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='amount',
            new_name='amount_usd',
        ),
    ]
