# Generated by Django 5.2.1 on 2025-09-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_rename_amount_withdrawalrequest_amount_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrowtransaction',
            old_name='amount',
            new_name='amount_usd',
        ),
    ]
