# Generated by Django 5.2.1 on 2025-09-26 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_currencyrate'),
        ('tasks', '0005_alter_submission_unique_together_and_more'),
        ('wallets', '0012_rename_amount_escrowtransaction_amount_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='wallets_esc_status_9a4169_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['created_at'], name='wallets_esc_created_b1920b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='wallets_tra_user_id_446087_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='wallets_tra_status_af050c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallets_tra_created_486ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user'], name='wallets_wit_user_id_61b4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='wallets_wit_status_8a21ce_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='wallets_wit_created_195af7_idx'),
        ),
    ]
