# Generated by Django 5.2.1 on 2025-09-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_escrowtransaction_wallets_esc_status_9a4169_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
