# Generated by Django 5.2.1 on 2025-09-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymenttransaction_options_and_more'),
        ('wallets', '0014_alter_withdrawalrequest_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttransaction'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
