# Generated by Django 5.2.1 on 2025-09-27 08:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_alter_withdrawalrequest_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
