# Generated by Django 5.2.1 on 2025-10-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0016_wallet_locked_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='locked_balance',
        ),
    ]
