# Generated by Django 5.2.1 on 2025-09-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_commission_to_tree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price', 'created_at']},
        ),
    ]
