# Generated by Django 5.2.1 on 2025-09-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='business_volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='daily_ad_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
