# Generated by Django 5.2.1 on 2025-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscriptionplan_business_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='affiliate_marketing',
            field=models.BooleanField(default=False, help_text='Can access affiliate marketing'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='hire_marketers',
            field=models.BooleanField(default=False, help_text='Can hire marketers'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='own_store',
            field=models.BooleanField(default=False, help_text='Can own an online store'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='daily_ad_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited daily tasks'),
        ),
    ]
