# Generated by Django 5.2.1 on 2025-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionplan_affiliate_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='business_volume',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Demo/Trial'), ('business', 'Business Member')], default='Business Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='affiliate_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='daily_ad_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='hire_marketers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='own_store',
            field=models.BooleanField(default=False),
        ),
    ]
