# Generated by Django 5.2.1 on 2025-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_subscriptionplan_business_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Demo/Trial'), ('business', 'Business Member')], max_length=20),
        ),
    ]
